"""bought property quantity added

Revision ID: 55ad8d2b84dd
Revises: f025cb9675fe
Create Date: 2023-07-05 11:17:32.720154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ad8d2b84dd'
down_revision = 'f025cb9675fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bought_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bought_properties', schema=None) as batch_op:
        batch_op.drop_column('bought_quantity')

    # ### end Alembic commands ###
