"""Renting option removed

Revision ID: a5df07a00164
Revises: c81973e882fb
Create Date: 2023-07-05 20:44:13.610674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5df07a00164'
down_revision = 'c81973e882fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bought_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Integer(), nullable=True))
        batch_op.drop_column('total_price')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('is_rental')
        batch_op.drop_column('is_sold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sold', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_rental', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('bought_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
