"""Bought property attribute added

Revision ID: c81973e882fb
Revises: 55ad8d2b84dd
Create Date: 2023-07-05 16:41:55.475379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81973e882fb'
down_revision = '55ad8d2b84dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bought_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bought_properties', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
